make:
	make -C ./mmap_socket_test/client
	make -C ./mmap_socket_test/server
	make -C ./parse1
clean:
	rm ./mmap_socket_test/client/target -rf
	rm ./mmap_socket_test/server/target -rf
	rm ./parse1/target -rf
