.PHONY: debug release

debug:
	CARGO_TARGET_DIR=../target cargo +nightly-2023-12-11-x86_64-unknown-linux-gnu build 

release:
	CARGO_TARGET_DIR=../target cargo +nightly-2023-12-11-x86_64-unknown-linux-gnu build --release

