.PHONY: debug release

debug:
	cargo build
	# CARGO_TARGET_DIR=../target cargo build

clean:
	cargo clean
	# CARGO_TARGET_DIR=../target cargo clean
release:
	cargo build --release
	# CARGO_TARGET_DIR=../target cargo build --release

